FROM baseimage_var

# set a directory for the app
WORKDIR /srv/www/

# copy all the files to the container
COPY . .

# tell the port number the container should expose
EXPOSE 80

ENV WORLD_VAR Arda

# run the command
ENTRYPOINT "./www.py"
