FROM baseimage_var

# set a directory for the app
WORKDIR /srv/www/

# copy all the files to the container
COPY . .
RUN mkdir templates/ && cp index.html templates

# install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# tell the port number the container should expose
EXPOSE 80

ENV WORLD_VAR Arda

# run the command
ENTRYPOINT ["python", "./app.py"]
