#!/usr/bin/env python3

# Python clone of `htpasswd -Bbn username password`

import sys
from passlib.apache import HtpasswdFile

if sys.argv[1] != "-Bbn" or len(sys.argv) != 4:
    sys.exit("ERROR: " + " ".join(sys.argv))

ht = HtpasswdFile(default_scheme="bcrypt")
ht.set_password(sys.argv[2], sys.argv[3])
print(ht.to_string().decode("utf-8"))
