ARG tag
FROM $tag
ARG pkgs
RUN zypper --gpg-auto-import-keys ref -s
RUN zypper install -y $pkgs
RUN (cd /usr/lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /usr/lib/systemd/system/multi-user.target.wants/*; \
rm -f /etc/systemd/system/*.wants/*; \
rm -f /usr/lib/systemd/system/local-fs.target.wants/*; \
rm -f /usr/lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /usr/lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /usr/lib/systemd/system/basic.target.wants/*; \
rm -f /usr/lib/systemd/system/anaconda.target.wants/*
COPY instance_389.inf /tmp/
RUN echo "root:test" | chpasswd
VOLUME ["/sys/fs/cgroup", "/run"]
CMD ["/sbin/init"]
