# Copyright 2026 SUSE LLC
# SPDX-License-Identifier: GPL-2.0-or-later

package Kernel::nvme;

use base Exporter;
use Exporter;

use strict;
use warnings;
use testapi;

our @EXPORT_OK = qw(
  nvme_target_control_script
  deploy_nvme_target_control
);

=encoding UTF-8

=head1 SYNOPSIS

Helpers for running blktests' NVMe-over-Fabrics tests against a real,
separate target machine instead of blktests' own same-host loopback
setup, via the C<NVME_TARGET_CONTROL> mechanism (see
L<blktests Documentation/running-tests.md|https://github.com/osandov/blktests>
and C<contrib/nvme_target_control.py> in the blktests source for the
upstream reference).

Unlike the upstream reference script (which drives a remote nvmetcli
REST API service and a static TOML config, since it assumes no other
coordination between initiator and target), these helpers assume the
target and initiator are two openQA multimachine SUTs already
synchronized via barriers, with direct root SSH access to each other
(the same access multimachine tests like NFS already rely on). The
generated script manipulates the target's C<nvmet> configfs tree
directly over SSH — no nvmetcli, no REST API service required on
either side.

=cut

=head2 nvme_target_control_script

  my $script = nvme_target_control_script(
      target_host => 'nvme-target-node00',
      target_addr => '192.168.42.10',
      blkdev      => '/dev/nvme0n1',
  );

Build the text of a C<NVME_TARGET_CONTROL>-compatible shell script,
implementing the C<setup>, C<cleanup>, and C<config> subcommands
blktests calls (see C<tests/nvme/rc> and C<common/nvme> in the blktests
source for the exact contract). C<add-ports> is accepted but left as a
stub, matching the upstream reference script — it is only needed by
multi-port ANA test cases, not the base NVMe-over-TCP flow.

C<setup> and C<cleanup> SSH into C<target_host> as root and create or
tear down, respectively: an nvmet subsystem, a namespace backed by
C<blkdev>, a TCP port bound to C<target_addr>:C<target_port>, and an
allowed host entry. C<config --show-*> reports back the arguments
given here — no discovery, no state kept beyond one setup/cleanup
cycle per subsystem.

Arguments:
  target_host - Hostname or IP blktests' initiator can SSH into as
                root to configure the real NVMe target. Required.
  blkdev      - Device or file path on the target host to expose as
                the namespace backing store (e.g. '/dev/nvme0n1').
                Required.
  target_addr - IP address blktests should connect to for NVMe/TCP
                traffic (the target's address on the dedicated test
                VLAN). Defaults to target_host — pass this separately
                whenever SSH management access and NVMe/TCP traffic
                use different addresses.
  target_port - TCP port for the target to listen on (addr_trsvcid).
                Default: 4420 (the IANA-assigned NVMe/TCP port).
  subsysnqn   - Subsystem NQN to create. Default: 'blktests-subsystem-1',
                matching blktests' typical default test subsystem.
  hostnqn     - Host NQN to allow. Default: a fixed
                'nqn.2014-08.org.nvmexpress:uuid:blktests-initiator'.
  hostid      - Host ID reported via 'config --show-hostid'. Default:
                a fixed placeholder UUID; only matters if a test cares
                about a stable, real hostid.
  adrfam      - Address family for the port. Default: 'ipv4'.

Returns: the script text. Use C<deploy_nvme_target_control> to write it
onto the initiator SUT and make it executable, or handle that yourself.

=cut

sub nvme_target_control_script {
    my (%args) = @_;
    my $target_host = $args{target_host} // die 'nvme_target_control_script requires target_host';
    my $blkdev = $args{blkdev} // die 'nvme_target_control_script requires blkdev';
    my $target_addr = $args{target_addr} // $target_host;
    my $target_port = $args{target_port} // 4420;
    my $subsysnqn = $args{subsysnqn} // 'blktests-subsystem-1';
    my $hostnqn = $args{hostnqn} // 'nqn.2014-08.org.nvmexpress:uuid:blktests-initiator';
    my $hostid = $args{hostid} // '4d6e6f74-6520-4120-7265-616c20504b';
    my $adrfam = $args{adrfam} // 'ipv4';

    return <<"SCRIPT";
#!/bin/bash
# Generated by Kernel::nvme::nvme_target_control_script - do not edit by hand.
# Implements the blktests NVME_TARGET_CONTROL contract against a real,
# separate NVMe target over SSH (nvmet configfs, no nvmetcli/REST API).
set -eu

TARGET_HOST='$target_host'
TARGET_ADDR='$target_addr'
TARGET_PORT='$target_port'
DEFAULT_SUBSYSNQN='$subsysnqn'
DEFAULT_HOSTNQN='$hostnqn'
DEFAULT_HOSTID='$hostid'
DEFAULT_BLKDEV='$blkdev'
ADRFAM='$adrfam'

ssh_target() {
    ssh -o BatchMode=yes -o StrictHostKeyChecking=no "root\@\${TARGET_HOST}" "\$1"
}

cmd_setup() {
    local subsysnqn="\$DEFAULT_SUBSYSNQN" hostnqn="\$DEFAULT_HOSTNQN"
    while [[ \$# -gt 0 ]]; do
        case \$1 in
            --subsysnqn) subsysnqn="\$2"; shift 2 ;;
            --hostnqn) hostnqn="\$2"; shift 2 ;;
            *) shift ;;
        esac
    done
    ssh_target "set -eu
NVMET_CFS=/sys/kernel/config/nvmet
mkdir -p \\\$NVMET_CFS/subsystems/\${subsysnqn}
echo 0 > \\\$NVMET_CFS/subsystems/\${subsysnqn}/attr_allow_any_host
mkdir \\\$NVMET_CFS/subsystems/\${subsysnqn}/namespaces/1
echo -n '\${DEFAULT_BLKDEV}' > \\\$NVMET_CFS/subsystems/\${subsysnqn}/namespaces/1/device_path
echo 1 > \\\$NVMET_CFS/subsystems/\${subsysnqn}/namespaces/1/enable
PORT=0
while [ -e \\\$NVMET_CFS/ports/\\\$PORT ]; do PORT=\\\$((PORT + 1)); done
mkdir \\\$NVMET_CFS/ports/\\\$PORT
echo tcp > \\\$NVMET_CFS/ports/\\\$PORT/addr_trtype
echo -n '\${TARGET_ADDR}' > \\\$NVMET_CFS/ports/\\\$PORT/addr_traddr
echo '\${ADRFAM}' > \\\$NVMET_CFS/ports/\\\$PORT/addr_adrfam
echo '\${TARGET_PORT}' > \\\$NVMET_CFS/ports/\\\$PORT/addr_trsvcid
ln -s \\\$NVMET_CFS/subsystems/\${subsysnqn} \\\$NVMET_CFS/ports/\\\$PORT/subsystems/\${subsysnqn}
mkdir -p \\\$NVMET_CFS/hosts/\${hostnqn}
ln -sf \\\$NVMET_CFS/hosts/\${hostnqn} \\\$NVMET_CFS/subsystems/\${subsysnqn}/allowed_hosts/\${hostnqn}
echo \\\$PORT > /run/nvmet-port-\${subsysnqn//\\//_}
"
}

cmd_add_ports() {
    echo "'nvme_target_control add-ports' is a stub" >&2
}

cmd_cleanup() {
    local subsysnqn="\$DEFAULT_SUBSYSNQN"
    while [[ \$# -gt 0 ]]; do
        case \$1 in
            --subsysnqn) subsysnqn="\$2"; shift 2 ;;
            *) shift ;;
        esac
    done
    ssh_target "set -eu
NVMET_CFS=/sys/kernel/config/nvmet
PORT=\\\$(cat /run/nvmet-port-\${subsysnqn//\\//_} 2>/dev/null || echo 0)
rm -f \\\$NVMET_CFS/ports/\\\$PORT/subsystems/\${subsysnqn} 2>/dev/null || true
echo 0 > \\\$NVMET_CFS/subsystems/\${subsysnqn}/namespaces/1/enable 2>/dev/null || true
rmdir \\\$NVMET_CFS/subsystems/\${subsysnqn}/namespaces/1 2>/dev/null || true
rm -f \\\$NVMET_CFS/subsystems/\${subsysnqn}/allowed_hosts/* 2>/dev/null || true
rmdir \\\$NVMET_CFS/subsystems/\${subsysnqn} 2>/dev/null || true
rmdir \\\$NVMET_CFS/ports/\\\$PORT 2>/dev/null || true
rm -f /run/nvmet-port-\${subsysnqn//\\//_}
" || true
}

cmd_config() {
    case "\${1:-}" in
        --show-trtype) echo tcp ;;
        --show-blkdev-type) echo device ;;
        --show-hostnqn) echo "\$DEFAULT_HOSTNQN" ;;
        --show-hostid) echo "\$DEFAULT_HOSTID" ;;
        --show-host-traddr) echo "" ;;
        --show-traddr) echo "\$TARGET_ADDR" ;;
        --show-trsvid) echo "\$TARGET_PORT" ;;
        --show-subsysnqn) echo "\$DEFAULT_SUBSYSNQN" ;;
        --show-subsys-uuid) echo "" ;;
        *) echo "Unknown config query: \${1:-}" >&2; exit 1 ;;
    esac
}

case "\${1:-}" in
    setup) shift; cmd_setup "\$\@" ;;
    add-ports) shift; cmd_add_ports "\$\@" ;;
    cleanup) shift; cmd_cleanup "\$\@" ;;
    config) shift; cmd_config "\$\@" ;;
    *) echo "Usage: \$0 {setup|add-ports|cleanup|config} [args...]" >&2; exit 1 ;;
esac
SCRIPT
}

=head2 deploy_nvme_target_control

  my $path = deploy_nvme_target_control('/usr/local/bin/nvme_target_control', target_host => ..., blkdev => ...);

Write the script built by C<nvme_target_control_script> (same
arguments) to C<$path> on the current SUT and make it executable.
Intended to run on the blktests initiator SUT, immediately before
setting C<NVME_TARGET_CONTROL=$path> and running C<./check nvme>.

Returns: C<$path>.

=cut

sub deploy_nvme_target_control {
    my ($path, %args) = @_;
    my $script = nvme_target_control_script(%args);

    assert_script_run("cat > $path <<'NVME_TARGET_CONTROL_EOF'\n${script}NVME_TARGET_CONTROL_EOF");
    assert_script_run("chmod +x $path");
    return $path;
}

1;
