# SUSE's openQA tests
#
# Copyright 2022 SUSE LLC
# SPDX-License-Identifier: FSFAP

# Summary: bci-tests log parser
#
#   This module is used to parse the result files generated by BCI-tests
#   tox commands.
#   BCI-tests produce separate XUnit results files for each environment.
#   This merges all files together into a single xml file that will
#   be used by OpenQA to represent the results in "External results"
# Maintainer: qa-c team <qa-c@suse.de>

use Mojo::Base 'opensusebasetest';
use XML::LibXML;
use testapi;
use serial_terminal 'select_serial_terminal';
use File::Basename;

sub run {
    my ($self) = @_;
    select_serial_terminal;

    my $dom = XML::LibXML::Document->new('1.0', 'utf-8');
    my $root = $dom->createElement('testsuites');
    $dom->setDocumentElement($root);
    my $result_files = script_output('find /root/BCI-tests -type f -name "junit_*.xml"');
    record_info('Files', $result_files);
    # Dump xml contents to a location where we can access later using data_url
    for my $file (split(/\n/, $result_files)) {
        # Each file will contain the engine as suffix, e.g. junit_minimal_docker.xml
        # We need to extract the container engine and the environment name
        (my $file_no_extension = $file) =~ s/.xml//;
        (my $file_no_prefix = $file_no_extension) =~ s/junit_*//;
        (my $env = $file_no_prefix) =~ s/\_.*//;
        (my $engine = $file_no_prefix) =~ s/.*\_//;
        my $log_file;
        eval {
            $log_file = upload_logs($file);
        };
        if ($@) {
            record_info('Skip', "Skipping results for $file. $@");
        } else {
            record_info('Parse', $log_file);
            my $dom = XML::LibXML->load_xml(location => "ulogs/$log_file");
            for my $node ($dom->findnodes('//testsuite')) {
                # Replace default attribute name "pytest" by its env name and engine
                my $new_name = $env . '_' . $engine;
                $node->{name} =~ s/pytest/$new_name/;
                # Append test results to the resulting xml file
                $root->appendChild($node);
            }
        }
    }
    $dom->toFile(hashed_string('result.xml'), 1);
    # Download file from host pool to the instance
    assert_script_run('curl -s ' . autoinst_url('/files/result.xml') . ' -o /tmp/result.txt');
    parse_extra_log('XUnit', '/tmp/result.txt');
}

1;
