#!/bin/bash
# combustion: network
# Redirect output to the console
exec > >(exec tee -a /dev/console) 2>&1
set -eux
echo Combustion was here > /usr/share/combustion-welcome
systemctl enable sshd.service
#disabled on MM because networking is not configured at boot stage
#curl conncheck.opensuse.org
systemctl restart getty@tty2.service
