#!/bin/bash
# METADATA_START
# ---
# test: policykit rules
# desc: Verifies functionality of policykit rules
# steps:
#   - check folder permissions /etc/polkit-1/rules.d/ , bail out if !root:polkitd
#   - save original hostname
#   - add a permissive polkit rule in /etc/polkit-1/rules.d/ and restart polkit service
#   - try to change hostname, should succeed (do not ask root password)
#   - ensure hostname has been changed
#   - remove polkit rule and restart service
#   - try to change hostname, should fail (will ask root password)
#   - ensure hostname has NOT been changed
#   - restore original hostname
# author: <andrea.manzini@suse.com>
# maintainer: QE Security <none@suse.de>
# expected: no errors raised, connection succeed
# platform: Tumbleweed
# tags: security polkit bsc#1249581
# ---
# METADATA_END

set -e

# Check for a metadata flag (-m or --metadata) as the first argument.
if [[ "$1" == "-m" || "$1" == "--metadata" ]]; then
    # If the flag is present, use awk to parse this script file ($0).
    # It finds the line with '# METADATA_START', starts printing every
    # subsequent line, and stops after hitting '# METADATA_END'.
    # This extracts the metadata block without including the markers themselves.
    awk '/# METADATA_END/{exit} f{print substr($0,3)}; /# METADATA_START/{f=1}' "$0"
    exit 0
fi

# If the metadata flag is not provided, run the tests as usual.

# ensure the program is running as root
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root."
    exit 1
fi

# ensure gotestsum is installed
if ! command -v gotestsum &> /dev/null; then
    echo "gotestsum could not be found, please install it first."
    exit 1
fi  

# empty the go test cache to avoid stale results
go clean -testcache
# run tests with gotestsum
exec gotestsum --format=standard-verbose --junitfile results.xml

