install: junit.sh pamtest.py testincl.sh
	mkdir -p "${DESTDIR}/usr/lib/testsuite"
	cp -R junit.sh krb ldap local ldap-inherited-groups ldap-nested-groups pamtest.py testincl.sh "${DESTDIR}/usr/lib/testsuite"
