#!/bin/bash
set -euo pipefail

ip_addr=$(ip n | awk '/192.168.122/ {print $1}')
if [[ -n "$ip_addr" ]] && nc -zvw2 $ip_addr 22 2>/dev/null; then
    echo "SSH is ONLINE"
    exit 0
else
    echo "SSH still OFFLINE"
    exit 1
fi
