#!/usr/bin/expect
 
# This script is used for access remote host via ssh and run some commands
# without interactive operations
# Usage: ssh_script [host] [user] [password]
# Reference: https://www.journaldev.com/1405/expect-script-ssh-example-tutorial
# Author: https://www.journaldev.com/author/pankaj

set a_exp $::env(TPM_CHK_CMD)
set timeout 60
spawn ssh [lindex $argv 1]@[lindex $argv 0]
expect "yes/no*" {
    send "yes\r"
    expect "*?assword" { send "[lindex $argv 2]\r" }
    } "*?assword" { send "[lindex $argv 2]\r" }

expect " #" { send "ls /dev/tpm*\r" }
expect " #" { send "$a_exp\r" }
expect " #" { send "exit\r" }
