#!/bin/sh
set -eu

n_users="$1"

for i in `seq 1 $n_users` ; do
	user="user${i}"
	# Loop until pkill no longer finds matching processes.
	while pkill -u "$user"; do sleep 1; done
	userdel -r "$user"
done
