#!/bin/sh -ex

uname -a
lsmod
free
cat /etc/fstab || echo "no /etc/fstab found"
mount
mount | grep -q '/ type btrfs' && /usr/sbin/btrfs filesystem df /
df -h
ip -o a s
ip r s
ip -6 r s
cat /etc/resolv.conf
ls -al /etc/sysconfig/network || true
rpm -qa 'kernel-*'
grep DISPLAYMANAGER /etc/sysconfig/displaymanager || true
grep DEFAULT /etc/sysconfig/windowmanager || true
ls -l /etc/ntp* || true
[ -f /var/log/messages ] && du /var/log/messages
ps ax
systemctl --no-pager --full
rpm -qa | sort
journalctl -a --no-full -m -o short-precise > /var/log/journal.dump
# explicitly ignore exit code as we know files can change in the mean time
tar cjf /tmp/logs.tar.bz2 --warning=no-file-changed /var/log || true
