---
name: default
description:    >
    Maintainer: qe-core <qe-core@suse.de>
    Standard scenario where we mainly just follow installation
    suggestions without any adjustments.
conditional_schedule:
    boot:
        ARCH:
            x86_64:
                - installation/isosize
                - '{{bootloader}}'
            s390x:
                - installation/bootloader_zkvm
            aarch64:
                - installation/isosize
                - installation/bootloader_uefi
            ppc64le:
                - installation/isosize
                - installation/bootloader
    bootloader:
        MACHINE:
            64bit:
                - installation/bootloader
            uefi:
                - installation/bootloader_uefi
            64bit-smp:
                - installation/bootloader
            svirt-hyperv:
                - installation/bootloader_hyperv
                - installation/bootloader
            svirt-hyperv-uefi:
                - installation/bootloader_hyperv
                - installation/bootloader_uefi
    grub_test:
        ARCH:
            x86_64:
                - installation/grub_test
            aarch64:
                - installation/grub_test
            ppc64le:
                - installation/grub_test
    mgmt_console:
        ARCH:
            s390x:
                - boot/reconnect_mgmt_console
    system_workarounds:
        ARCH:
            aarch64:
                - installation/system_workarounds
    glibc_sanity:
        ARCH:
            x86_64:
                - console/glibc_sanity
schedule:
    - '{{boot}}'
    - installation/welcome
    - installation/accept_license
    - installation/scc_registration
    - installation/addon_products_sle
    - installation/system_role
    - installation/partitioning
    - installation/partitioning_finish
    - installation/installer_timezone
    - installation/user_settings
    - installation/user_settings_root
    - installation/resolve_dependency_issues
    - installation/installation_overview
    - installation/disable_grub_timeout
    - installation/start_install
    - installation/await_install
    - installation/logs_from_installation_system
    - installation/reboot_after_installation
    - '{{grub_test}}'
    - '{{mgmt_console}}'
    - installation/first_boot
    - '{{system_workarounds}}'
    - console/system_prepare
    - console/check_network
    - console/system_state
    - console/prepare_test_data
    - console/consoletest_setup
    - locale/keymap_or_locale
    - console/force_scheduled_tasks
    - console/textinfo
    - console/hostname
    - console/installation_snapshots
    - console/curl_https
    - console/salt
    - '{{glibc_sanity}}'
    - console/glibc_tunables
    - update/zypper_up
    - console/vim
    - console/firewall_enabled
    - console/sshd
    - console/ssh_cleanup
    - console/mtab
    - console/mariadb_srv
    - console/rsync
    - console/http_srv
    - console/apache
    - console/dns_srv
    - console/postgresql_server
    - console/shibboleth
    - console/apache_ssl
    - console/apache_nss
    - console/consoletest_finish
...
