#!/bin/bash -e

success=1
JSONNET_FILES=$(git ls-files data/ | grep '.json\?net$' | xargs)

if test -n "$JSONNET_FILES"; then
    for file in $JSONNET_FILES; do
        if ! python3 -c "import _jsonnet; _jsonnet.evaluate_file('$file'); print('OK: $file')"; then
            success=0
        fi
    done
else
    echo "No jsonnets modified."
fi

[ $success = 1 ] && echo "check_jsonnet SUCCESS" && exit 0
exit 1
