#!/bin/sh -e
echo "$TRAVIS_PULL_REQUEST"
echo "${TRAVIS_REPO_SLUG}"
echo "${GITHUB_PAT}"
if [ "$TRAVIS_PULL_REQUEST" != "false" ] ; then
curl -H "Authorization: token ${GITHUB_PAT}" -X POST \
-d "{\"body\": \"Warning: staging tests might be broken\"}" \
"https://api.github.com/repos/${TRAVIS_REPO_SLUG}/issues/${TRAVIS_PULL_REQUEST}/comments"
fi
