#!/bin/bash -e

FILES=$(git ls-files data/ | grep -v 'wsl' | xargs echo)

for file in $FILES; do
    if grep -E -i -r "nots3cr3t" "$file"; then
        echo "Find hardcode password at $file" 
	exit 1
    fi
done
echo "check hardcode password SUCCESS" && exit 0
