#!/bin/sh -e

for test in $(git ls-files "*tests/*.pm") ; do
    t=$(echo $test | sed -e 's@tests/.*/@@' -e 's@.pm@@')
    git grep -q $t || echo $test
done | grep -v 'qa_automation'
git rm -f main.pm >/dev/null 2>&1
