#!/usr/bin/env perl
use strict;
use warnings;
use FindBin '$Bin';
use Test::More;
use YAML::PP;
use JSON::Validator;
use File::Basename;
use YAML::PP::Schema::Include;

my $schema_file = "$Bin/../t/schema/Schedule-1.yaml";
my $validator = JSON::Validator->new;
$validator = eval { $validator->load_and_validate_schema($schema_file) };
if (my $err = $@) {
    diag $err;
    BAIL_OUT("Schema $schema_file invalid");
}

pass("Nothing to do") unless @ARGV;
my $root_project_dir = dirname(__FILE__) . '/../';

my $include = YAML::PP::Schema::Include->new(paths => ($root_project_dir));
my $ypp     = YAML::PP->new(schema => ['Core', $include, 'Merge']);
$include->yp($ypp);
for my $file (@ARGV) {
    my $data = eval {
        $ypp->load_file($file);
    };
    if (my $err = $@) {
        fail("$file has invalid yaml syntax");
        diag "Error: $err";
    }
    else {
        pass("$file has valid yaml syntax");
    }
    if ($file =~ m{schedule/}) {
        my @errors = $validator->validate($data);
        is(scalar @errors, 0, "$file passes schema validation")
            or diag @errors;
    }
}

done_testing();
