#!/usr/bin/env perl
use Test::More;
use YAML::PP;

pass("No yaml files modified") unless @ARGV;
for my $file (@ARGV) {
    eval { YAML::PP::LoadFile($file) };
    if (my $err = $@) {
        fail("$file has invalid yaml syntax");
        diag "Error: $err";
    }
    else {
        pass("$file has valid yaml syntax");
    }
}
done_testing();
