#!/bin/sh -e

FILES="${@}"
success=1
for FILE in $FILES; do
    if [ -f "$FILE" ]; then
        # if file exists it means it was renamed, and then original file name is retrieved by git log
        FILE=$(git log --follow -p $FILE | grep 'rename from test_data/')
    fi
    if MATCHED_SCHEDULE_FILES="$(grep --recursive --ignore-case --files-with-matches "$FILE\b" schedule/)"
    then
        echo -e "\"$FILE\" test data file was removed or renamed, but it is still used in: \
        \n$MATCHED_SCHEDULE_FILES\n"
        success=0
    fi
done
[ $success = 1 ] && echo "SUCCESS" && exit 0
exit 1

