#!/bin/bash
set -euxo pipefail

grub2_config() {
    file=/etc/default/grub
    sed -i 's/^\s*GRUB_TIMEOUT=.*$/GRUB_TIMEOUT=15/g' $file
    sed -i -r 's/^(\s|#)*GRUB_TERMINAL=.*$/GRUB_TERMINAL="gfxterm console"/g' $file
    sed -i 's/console=tty0//g' $file
    sed -i 's/console=tty[^ ]*/console=SERIALCONSOLE,115200/g' $file
    echo "DEBUG: now $file is,"
    cat $file
    grub2-mkconfig -o /boot/grub2/grub.cfg
    # Set boot to sl-secureboot entry -- newly installed SL Micro
    bootnum=$(efibootmgr | grep sl-secureboot | grep -o "^Boot[^\s]*" | sed -e 's/Boot//' -e 's/\*//')
    efibootmgr -o $bootnum
}

# Redirect output to the console
# Comment off to workaround https://bugzilla.suse.com/show_bug.cgi?id=1222411#c9
# exec > >(exec tee -a /dev/SERIALCONSOLE) 2>&1
    grub2_config # Configure grub2 in the system

