# SUSE's openQA tests
#
# Copyright 2022 SUSE LLC
# SPDX-License-Identifier: FSFAP
#
# Summary: Run 'AppArmor negative test' test case of ATSec test suite
# Maintainer: QE Security <none@suse.de>
# Tags: poo#109307

use base 'consoletest';
use strict;
use warnings;
use testapi;
use utils;
use audit_test 'parse_kvm_svirt_apparmor_results';

sub run {
    my ($self) = shift;

    select_console 'root-console';
    assert_script_run("cd $audit_test::test_dir/audit-test/kvm_svirt_apparmor/tests");

    # Cleanup the log files which are generated by last test
    script_run('rm -rf /tmp/vm-sep/');

    # Modify the test code
    my $test_file = 'vm-sep';
    assert_script_run("sed -i 's/^\\tload_profile\$/#&/g' $test_file");
    assert_script_run("sed -i 's/^\\tsanity\$/#&/g' vm-sep-crack");

    # Run the test script
    script_run("./$test_file", timeout => 120);

    # Parse the log file
    my $result = parse_kvm_svirt_apparmor_results('apparmor_negative_test');
    $self->result($result);
}

sub test_flags {
    return {always_rollback => 1};
}

1;
