# SUSE's openQA tests
#
# Copyright 2022 SUSE LLC
# SPDX-License-Identifier: FSFAP
#
# Summary: Run 'AppArmor negative test' test case of EAL4 test suite
# Maintainer: QE Security <none@suse.de>
# Tags: poo#109307

use Mojo::Base 'consoletest';
use testapi;
use utils;
use audit_test 'parse_kvm_svirt_apparmor_results';

my @patched_files = qw(vm-sep vm-sep-crack);

sub tests_dir { "$audit_test::test_dir/audit-test/kvm_svirt_apparmor/tests" }

sub restore_test_files {
    # run() comments out steps in the upstream test scripts with 'sed -i'. That checkout is
    # shared with the other kvm_svirt_apparmor modules and the suite registers no cleanup of
    # its own, so put the originals back instead of leaving patched scripts behind.
    my $dir = tests_dir;
    script_run("test -e $dir/$_.orig && mv -f $dir/$_.orig $dir/$_") foreach @patched_files;
}

sub run {
    my ($self) = shift;

    select_console 'root-console';
    assert_script_run('cd ' . tests_dir);

    # Cleanup the log files which are generated by last test
    script_run('rm -rf /tmp/vm-sep/');

    # Keep a pristine copy so the modifications below can be reverted afterwards
    assert_script_run("cp -a $_ $_.orig") foreach @patched_files;

    # Modify the test code
    my $test_file = 'vm-sep';
    assert_script_run("sed -i 's/^\\tload_profile\$/#&/g' $test_file");
    assert_script_run("sed -i 's/^\\tsanity\$/#&/g' vm-sep-crack");

    # Run the test script
    script_run("./$test_file", timeout => 120);

    # Parse the log file
    my $result = parse_kvm_svirt_apparmor_results('apparmor_negative_test');
    $self->result($result);
}

sub post_run_hook {
    my ($self) = @_;
    restore_test_files;
    $self->SUPER::post_run_hook;
}

sub post_fail_hook {
    my ($self) = @_;
    restore_test_files;
    $self->SUPER::post_fail_hook;
}

1;
