name: Deploy documentation
permissions:
  contents: write

on:
  push:
    branches:
      - master

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v6
    - name: "CI: Generate documentation"
      run: script/generateLibDocs.sh
    - name: "CI: Deploy documentation"
      uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
