name: shellcheck
on:
  push:
    paths:
      - 'data/publiccloud/**'
  pull_request:
    paths:
      - 'data/publiccloud/**'
permissions: {}
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v6
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@00b27aa7cb85167568cb48a3838b75f4265f2bca  # master
        with:
          scandir: './data/publiccloud' 
